---
title: NASA - Water Resources
summary: How can remote sensing and data fusion help water resource managers?
share: FALSE
author: "Matt"
date: "2022-10-01"
tags:
doi: ""
url_pdf: ""
details: 
keywords: ""
show_date: FALSE
thumbnail: 'featured.png'
image:
  preview_only: FALSE
output: 
  html_document
---

## How can remote sensing and data fusion help water resource managers?

<br>

The objective of this proposal is to overcome historic barriers that prevent water resources managers from using remote sensing  into decision making process of water resource management in Northern Colorado (Fig. 1). To accomplish this task, we will build on existing collaborations with: Northern Water and the cities of Fort Collins and Greeley, who, together, supply wate to over 1 million residents in Northern Colorado. However, like most of the Western United States, these water supplies are dually threatened by impacts to water quantity and quality. Harmful algae blooms, increased sedimentation of supply reservoirs and highly varying concentrations of dissolved organic carbon, can all interfere with a water suppliers ability to provide clean drinking water to their customers. Here, We propose a project to use machine learning, remote sensing, and live-streaming sensors to build a system that predicts water quality at seasonal and weekly timescales. 
