---
title: Lower Poudre
summary: How does the Cache la Poudre River change as it travels through Fort Collins, Colorado?
profile: true
show_date: FALSE
share: FALSE
author: "Katie"
date: "2020-08-01"
tags:
doi: ""
url_pdf: ""
details: 
keywords: ""
thumbnail: 'featured.png'
image:
  preview_only: FALSE
output: 
  html_document
---

## How does the Cache la Poudre River change as it travels through Fort Collins, Colorado?

<br>

The Cache la Poudre River Monitoring Network is a collection of river monitoring sites strategically located throughout and directly upstream of the City of Fort Collins. Established in 2019, this network represents a unique public-private partnership between the City’s storm water and water quality divisions, the ROSS lab, and In-Situ Inc., a water monitoring equipment manufacturer based in Fort Collins. This monitoring partnership was spurred by the 2018 fish kill through the city, whose source was never determined. With a network of sensors now deployed, we can better track changes in water quality like those experienced in 2018 and understand how the river is influenced by its myriad of urban and agricultural inputs.