---
title: NASA - Illinois and Ohio River Watersheds
summary: How and why do algae blooms move through river and reservoir networks? 
share: FALSE
author: "Matt"
date: "2022-10-01"
tags:
doi: ""
url_pdf: ""
details: 
keywords: ""
thumbnail: 'featured.png'
image:
  preview_only: FALSE
output: 
  html_document
---

## How and why do algae blooms move through river and reservoir networks?

<br>

Understanding and predicting algal blooms in river systems requires a "network" perspective that takes into account hydrologic connectivity as well as variability in dominant controls over blooms such as river discharge, temperature, sunlight, and nutrients. No one approach-satellite observations, in-situ sensors, or modeling-can be used to both measure algal blooms and quantify the antecedent bloom conditions over both time and space. Therefore, we propose to close major methodological and conceptual gaps in remote sensing, machine learning modeling, and understanding algal blooms in rivers and reservoir using a cutting-edge monitoring platform that will provide chlorophyll-a (chl-a) observations (a proxy for algal blooms) at the spatial and temporal density required to understand why, where, when, and how riverine and river/reservoir algal blooms occur. To accomplish this goal we will produce daily estimates of chl-a by fusing continuous sensor, grab sample, and environmental driver data (e.g. discharge, temperature, climate etc.) with Landsat OLI and Sentinel-2 observations of chl-a within a hydrologic-network-aware Process Guided Deep Learning model (PGDL, Jia et al., 2021). Our objectives include,

1)  Build chl-a database across all rivers/reservoirs using satellite imagery. 2
2)  Develop PGDL model fusing in-situ and satellite data to generate chl-a database with a daily temporal resolution and spatial resolution equal to the National Hydrography Database to identify algal bloom.
3)  Interpret PGDL model to identify the antecedent conditions over time and space that lead to algal blooms.

We focus on two bloom-prone systems: the Ohio River Basin and the Illinois River Basin. These are ideal locations to develop and test our approach since the Illinois Basin is a focal area for USGS Next Generation Observing System focused on blooms, and the Ohio River is relatively data sparse to test transferability of our approach. Our overarching science question is: what are the antecedent conditions over time and space that are linked to algal bloom occurrence and severity in rivers and reservoirs?
