---
title: Upper Poudre
summary: How do wildfires affect water quality and algal growth in high elevation reservoirs, and are those changes propagated downstream?
share: FALSE
author: "Sam"
date: "2021-03-01"
tags:
doi: ""
url_pdf: ""
details: 
show_date: FALSE
keywords: ""
links:
  - icon_pack: fab
    icon: github
    name: Project Repository
    url: 'https://github.com/rossyndicate/cameron_peak_fire_study'
thumbnail: 'featured.png'
image:
  preview_only: FALSE
output: 
  html_document
---

## How do wildfires affect water quality and algal growth in high elevation reservoirs, and are those changes propagated downstream?

<br>

The 2020 Cameron Peak wildfire (CPF) was the largest wildfire in Colorado history at over 200,000 acres. The CPF burned a large proportion of the Cache la Poudre watershed, in particular areas surrounding high elevation reservoirs. This work is funded to support ongoing source water protection programs by the City of Fort Collins, Greeley, Thornton and Northern Water. In collaboration with the Rocky Mountain Research Station (USFS, RMRS), we are sampling various reservoir, tributary, and mainstem sites of the Cache la Poudre watershed. This field campaign allows us to analyze trends in water quality focusing on nutrients and other key constituents mobilized post-fire. The goal of this project is to understand how these nutrients affect algal growth in reservoirs and how those changes are propagated downstream. The reservoirs studied are the following: Barnes Meadow Reservoir, Chambers Lake, Comanche Reservoir, Hourglass Reservoir, Joe Wright Reservoir, Long Draw Reservoir, and Peterson Lake. Historical data (prior to 2021) was collected by the Rhoades Lab at the USFS' Rocky Mountain Research Station. Using this field data, we are working to create a system that will predict algal blooms before they occur using a combination of in-stream sensors, remote sensing, and field sampling.
