---
title: Life After Fire
summary: This workshop series will make transdisciplinary connections amongst scientists researching the environmental impact of the largest wildifres in Colorado history and engage the public with their findings. 
share: FALSE
author: "Anika"
date: "2022-10-31"
tags:
doi: ""
url_pdf: ""
details: 
keywords: ""
thumbnail: 'featured.png'
image:
  preview_only: FALSE
output: 
  html_document
---

## This workshop series will make transdisciplinary connections amongst scientists researching the environmental impact of the largest wildifres in Colorado history and engage the public with their findings. 

<br>

Since the Cameron Peak and East Troublesome Fires burned more than 400,000 acres of land west of Fort Collins, Colorado State University scientists and their local partners have been researching their direct impacts on our environment.The ROSS Lab and the Geospatial Centroid at CSU are hosting a three-series event to hear directly from ~10 different research teams as they assess the effects of these catastrophic, high-elevation wildfires on local fisheries, water quality, water quantity, and ecosystem recovery. These workshops have two aims, 1) promote collaboration across scientific disciplines so we can better understand and respond to these fire events in the future and 2) engage the public with these findings. 